### ISSUE TITLE
Json-lines streaming checksum

### ISSUE THREAD

**Issue by bambulin** [whalebone/recagen#8]
Recently @rattuscz made a good note about json-lines streaming: 
If the json-lines stream is interrupted just at the end of a line there's no way for the client to recognise whether it was the correct end of the stream or an unexpected stream interruption. It would be good to implement some kind of checksum so the client can verify if all the lines have been received properly. I.e. first json line of the stream can be some kind of header which would define how many significant json lines would be expected or we could implement something like https://en.wikipedia.org/wiki/Fletcher%27s_checksum (mentioned by @rattuscz)

@Narzhan it's related to the domain contents REST service as well as IoC archive json-lines REST service.
@rattuscz it's related to resolver config endpoint of portal
@robcza FYI

**Comment by Narzhan** [comment]
Prepared in [927188a](https://github.com/whalebone/content-processor/commit/927188a08c7ddb5858793d84eb65e97f2bc42301)

**Comment by rattuscz** [comment]
Prepared in a6f0c0a811a55cf72e1b37503d5a740334421ec7 (feature/shrimps), waiting for greenlight

**Comment by bambulin** [comment]
Ready in 2f97180c3506e5ea7838b23c72f28f6e7380982d
